# -*- coding: utf-8 -*-
"""matematika1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jHlwa8PpwK0c1doc0-OMh6UX4vFRhLT-
"""

PI = 3.14

def luas_lingkaran(jari_jari):
    luas_lingkaran = PI * jari_jari * jari_jari
    return luas_lingkaran

def luas_persegi(sisi):
    luas_persegi = sisi * sisi
    return luas_persegi